### ISSUE TITLE
P2P code review

### ISSUE THREAD

**Issue by dili021** [dili021/weather-app#3]

**Comment by rammazzoti2000** [comment]
Hey Stefan :wave: 
Nice project, the code is well structured, and the design is beautiful.
What you could do in your `fetch.js` for the error, instead of using `console.log(err);`, you could do like:
      ```alert('Input a valid city name!');``` 
      ```throw new Error(err.message);``` this would actually help for debugging and would also  prevent the app to go to the next step unless you provide a valid city name
